basePath: /
definitions:
  model.Auth:
    properties:
      name:
        description: |-
          Name
          in: string
        type: string
      password:
        description: |-
          Password
          in: string
        type: string
    type: object
  model.User:
    properties:
      age:
        description: |-
          Age
          in: int32
        type: integer
      datecreated:
        description: |-
          DateCreated
          in: date
        type: string
      firstname:
        description: |-
          Firstname
          in: string
        type: string
      id:
        description: |-
          Id
          in: int32
        type: integer
      name:
        description: |-
          Name
          in: string
        type: string
      password:
        description: |-
          Password
          in: string
        type: string
      token:
        description: |-
          Token
          in: string
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: julien.tellier@openwt.com
    name: API Support
  description: This is a sample service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Article API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: login user
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: login
      tags:
      - login
  /restricted/create-user:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: login user
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - Bearer: []
      summary: Return Users
      tags:
      - id
  /restricted/users:
    get:
      consumes:
      - application/json
      description: Return All Users
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - Bearer: []
      summary: Return All Users
      tags:
      - id
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
